      - name: Upload to PlanetHoster via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git/**
            **/.github/**
            **/README.md
            **/CHATGPT_CONTEXT.md
            **/*.md
            **/.DS_Store
            **/uploads/**
          log-level: verbose
